//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZWave.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZWave.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS.
        /// </summary>
        internal static string Abs {
            get {
                return ResourceManager.GetString("Abs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accel.
        /// </summary>
        internal static string Accel {
            get {
                return ResourceManager.GetString("Accel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration.
        /// </summary>
        internal static string Acceleration {
            get {
                return ResourceManager.GetString("Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration Feed Foward.
        /// </summary>
        internal static string AccelerationFeedFoward {
            get {
                return ResourceManager.GetString("AccelerationFeedFoward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is disabled. Please contact the Administrator..
        /// </summary>
        internal static string AccountDisabledMessage {
            get {
                return ResourceManager.GetString("AccountDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge.
        /// </summary>
        internal static string Acknowledge {
            get {
                return ResourceManager.GetString("Acknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user.
        /// </summary>
        internal static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Description.
        /// </summary>
        internal static string AlarmDescription {
            get {
                return ResourceManager.GetString("AlarmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarms.
        /// </summary>
        internal static string Alarms {
            get {
                return ResourceManager.GetString("Alarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle Extent.
        /// </summary>
        internal static string AngExtent {
            get {
                return ResourceManager.GetString("AngExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle Start.
        /// </summary>
        internal static string AngStart {
            get {
                return ResourceManager.GetString("AngStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle Step.
        /// </summary>
        internal static string AngStep {
            get {
                return ResourceManager.GetString("AngStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenuator Percentage.
        /// </summary>
        internal static string AttenuatorPercentage {
            get {
                return ResourceManager.GetString("AttenuatorPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto - Calibration.
        /// </summary>
        internal static string AutoCalib {
            get {
                return ResourceManager.GetString("AutoCalib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis.
        /// </summary>
        internal static string Axis {
            get {
                return ResourceManager.GetString("Axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accel:.
        /// </summary>
        internal static string AxisAccelLabel {
            get {
                return ResourceManager.GetString("AxisAccelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis Control.
        /// </summary>
        internal static string AxisControl {
            get {
                return ResourceManager.GetString("AxisControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jerk:.
        /// </summary>
        internal static string AxisJerkLabel {
            get {
                return ResourceManager.GetString("AxisJerkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis Name.
        /// </summary>
        internal static string AxisName {
            get {
                return ResourceManager.GetString("AxisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an axis.
        /// </summary>
        internal static string AxisPickerPlaceholder {
            get {
                return ResourceManager.GetString("AxisPickerPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        internal static string AxisPositionLabel {
            get {
                return ResourceManager.GetString("AxisPositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity:.
        /// </summary>
        internal static string AxisVelocityLabel {
            get {
                return ResourceManager.GetString("AxisVelocityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BiQuad 1 Filter.
        /// </summary>
        internal static string BiQuad1Filter {
            get {
                return ResourceManager.GetString("BiQuad1Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BiQuad 2 Filter.
        /// </summary>
        internal static string BiQuad2Filter {
            get {
                return ResourceManager.GetString("BiQuad2Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Level.
        /// </summary>
        internal static string BlackLevel {
            get {
                return ResourceManager.GetString("BlackLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        internal static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burst control.
        /// </summary>
        internal static string BurstControl {
            get {
                return ResourceManager.GetString("BurstControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration.
        /// </summary>
        internal static string Calibration {
            get {
                return ResourceManager.GetString("Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Change.
        /// </summary>
        internal static string CameraChange {
            get {
                return ResourceManager.GetString("CameraChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causeway System.
        /// </summary>
        internal static string CausewaySystem {
            get {
                return ResourceManager.GetString("CausewaySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        internal static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column 1.
        /// </summary>
        internal static string Column1 {
            get {
                return ResourceManager.GetString("Column1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column 2.
        /// </summary>
        internal static string Column2 {
            get {
                return ResourceManager.GetString("Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column center.
        /// </summary>
        internal static string ColumnCenter {
            get {
                return ResourceManager.GetString("ColumnCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command position.
        /// </summary>
        internal static string CommandPosition {
            get {
                return ResourceManager.GetString("CommandPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure role access.
        /// </summary>
        internal static string ConfigureRoleAccess {
            get {
                return ResourceManager.GetString("ConfigureRoleAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control profile.
        /// </summary>
        internal static string ControlProfile {
            get {
                return ResourceManager.GetString("ControlProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Settings.
        /// </summary>
        internal static string ControlSettings {
            get {
                return ResourceManager.GetString("ControlSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create NCC Operator.
        /// </summary>
        internal static string CreateNCCOperator {
            get {
                return ResourceManager.GetString("CreateNCCOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Cycles.
        /// </summary>
        internal static string CurrentCycles {
            get {
                return ResourceManager.GetString("CurrentCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Loops (Basic Tunning).
        /// </summary>
        internal static string CurrentLoops {
            get {
                return ResourceManager.GetString("CurrentLoops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Position.
        /// </summary>
        internal static string CurrentPosition {
            get {
                return ResourceManager.GetString("CurrentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datalog.
        /// </summary>
        internal static string Datalog {
            get {
                return ResourceManager.GetString("Datalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        internal static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        internal static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Result.
        /// </summary>
        internal static string DiscardResult {
            get {
                return ResourceManager.GetString("DiscardResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donor Chuck Vacuum.
        /// </summary>
        internal static string DonorChuckVacuum {
            get {
                return ResourceManager.GetString("DonorChuckVacuum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donor Lifting Module.
        /// </summary>
        internal static string DonorLiftingModule {
            get {
                return ResourceManager.GetString("DonorLiftingModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        internal static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw shape.
        /// </summary>
        internal static string DrawShape {
            get {
                return ResourceManager.GetString("DrawShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        internal static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse.
        /// </summary>
        internal static string Ellipse {
            get {
                return ResourceManager.GetString("Ellipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emission.
        /// </summary>
        internal static string Emission {
            get {
                return ResourceManager.GetString("Emission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder position.
        /// </summary>
        internal static string EncoderPosition {
            get {
                return ResourceManager.GetString("EncoderPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope control N.
        /// </summary>
        internal static string EnvelopeControlN {
            get {
                return ResourceManager.GetString("EnvelopeControlN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope control P.
        /// </summary>
        internal static string EnvelopeControlP {
            get {
                return ResourceManager.GetString("EnvelopeControlP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Code.
        /// </summary>
        internal static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Description.
        /// </summary>
        internal static string ErrorDescription {
            get {
                return ResourceManager.GetString("ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Description Placeholder.
        /// </summary>
        internal static string ErrorDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("ErrorDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Guide.
        /// </summary>
        internal static string ErrorGuide {
            get {
                return ResourceManager.GetString("ErrorGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Guide Placeholder.
        /// </summary>
        internal static string ErrorGuidePlaceholder {
            get {
                return ResourceManager.GetString("ErrorGuidePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occured. Please contact the Administrator..
        /// </summary>
        internal static string ErrorOccuredMessage {
            get {
                return ResourceManager.GetString("ErrorOccuredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check if the connection configuration is correct and the server is operational..
        /// </summary>
        internal static string EstablishServerConnectionErrorContent {
            get {
                return ResourceManager.GetString("EstablishServerConnectionErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Server Failed.
        /// </summary>
        internal static string EstablishServerConnectionErrorTitle {
            get {
                return ResourceManager.GetString("EstablishServerConnectionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated cycle time.
        /// </summary>
        internal static string EstimatedCycleTime {
            get {
                return ResourceManager.GetString("EstimatedCycleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EStop.
        /// </summary>
        internal static string EStop {
            get {
                return ResourceManager.GetString("EStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est. Time (s).
        /// </summary>
        internal static string EstTime {
            get {
                return ResourceManager.GetString("EstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure Time.
        /// </summary>
        internal static string ExposureTime {
            get {
                return ResourceManager.GetString("ExposureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External controls.
        /// </summary>
        internal static string ExternalControls {
            get {
                return ResourceManager.GetString("ExternalControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder:.
        /// </summary>
        internal static string FolderPth {
            get {
                return ResourceManager.GetString("FolderPth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency pulse divider.
        /// </summary>
        internal static string FrequencyPulseDivider {
            get {
                return ResourceManager.GetString("FrequencyPulseDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain.
        /// </summary>
        internal static string Gain {
            get {
                return ResourceManager.GetString("Gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gains.
        /// </summary>
        internal static string Gains {
            get {
                return ResourceManager.GetString("Gains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma.
        /// </summary>
        internal static string Gamma {
            get {
                return ResourceManager.GetString("Gamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home All.
        /// </summary>
        internal static string HomeAll {
            get {
                return ResourceManager.GetString("HomeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Sensor.
        /// </summary>
        internal static string HomeSensor {
            get {
                return ResourceManager.GetString("HomeSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Keeping.
        /// </summary>
        internal static string HouseKeeping {
            get {
                return ResourceManager.GetString("HouseKeeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect IP address configuration. Please update configuration and restart app to reconnect..
        /// </summary>
        internal static string IncorrectIPAddressConfigurationContent {
            get {
                return ResourceManager.GetString("IncorrectIPAddressConfigurationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to server failed.
        /// </summary>
        internal static string IncorrectIPAddressConfigurationTittle {
            get {
                return ResourceManager.GetString("IncorrectIPAddressConfigurationTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Vision.
        /// </summary>
        internal static string InspectionVision {
            get {
                return ResourceManager.GetString("InspectionVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intergrator Gain.
        /// </summary>
        internal static string IntergratorGain {
            get {
                return ResourceManager.GetString("IntergratorGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I (Intergrator Gain).
        /// </summary>
        internal static string IntergratorGainWithShortName {
            get {
                return ResourceManager.GetString("IntergratorGainWithShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is BiQuad Filter Selected?.
        /// </summary>
        internal static string IsBiQuadFilterSelected {
            get {
                return ResourceManager.GetString("IsBiQuadFilterSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Low Pass Selected?.
        /// </summary>
        internal static string IsLowPassSelected {
            get {
                return ResourceManager.GetString("IsLowPassSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Notch Filter Selected?.
        /// </summary>
        internal static string IsNotchFilterSelected {
            get {
                return ResourceManager.GetString("IsNotchFilterSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jerk.
        /// </summary>
        internal static string Jerk {
            get {
                return ResourceManager.GetString("Jerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser.
        /// </summary>
        internal static string Laser {
            get {
                return ResourceManager.GetString("Laser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser connection.
        /// </summary>
        internal static string LaserConnection {
            get {
                return ResourceManager.GetString("LaserConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Engine.
        /// </summary>
        internal static string LaserEngine {
            get {
                return ResourceManager.GetString("LaserEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Name.
        /// </summary>
        internal static string LaserName {
            get {
                return ResourceManager.GetString("LaserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser operation.
        /// </summary>
        internal static string LaserOperation {
            get {
                return ResourceManager.GetString("LaserOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser power - energy.
        /// </summary>
        internal static string LaserPowerEnergy {
            get {
                return ResourceManager.GetString("LaserPowerEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login.
        /// </summary>
        internal static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit sensor (-).
        /// </summary>
        internal static string LimitSensorNegative {
            get {
                return ResourceManager.GetString("LimitSensorNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit sensor (+).
        /// </summary>
        internal static string LimitSensorPositive {
            get {
                return ResourceManager.GetString("LimitSensorPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        internal static string Live {
            get {
                return ResourceManager.GetString("Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Streaming Action.
        /// </summary>
        internal static string LiveStreamingAction {
            get {
                return ResourceManager.GetString("LiveStreamingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Motion.
        /// </summary>
        internal static string LogMotion {
            get {
                return ResourceManager.GetString("LogMotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Pass Filter.
        /// </summary>
        internal static string LowPassFilter {
            get {
                return ResourceManager.GetString("LowPassFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to Machine has been lost. Please try again later or contact the Administrator..
        /// </summary>
        internal static string MachineConnectionLostContent {
            get {
                return ResourceManager.GetString("MachineConnectionLostContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to Machine lost.
        /// </summary>
        internal static string MachineConnectionLostTitle {
            get {
                return ResourceManager.GetString("MachineConnectionLostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main 1.
        /// </summary>
        internal static string Main1 {
            get {
                return ResourceManager.GetString("Main1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main 2.
        /// </summary>
        internal static string Main2 {
            get {
                return ResourceManager.GetString("Main2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message in this area.
        /// </summary>
        internal static string MessageAreaPlaceholder {
            get {
                return ResourceManager.GetString("MessageAreaPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric.
        /// </summary>
        internal static string Metric {
            get {
                return ResourceManager.GetString("Metric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing steps.
        /// </summary>
        internal static string MissingSteps {
            get {
                return ResourceManager.GetString("MissingSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model ID Selection.
        /// </summary>
        internal static string ModelIDSelection {
            get {
                return ResourceManager.GetString("ModelIDSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Selection.
        /// </summary>
        internal static string ModelSelection {
            get {
                return ResourceManager.GetString("ModelSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module 1.
        /// </summary>
        internal static string Module1 {
            get {
                return ResourceManager.GetString("Module1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module 2.
        /// </summary>
        internal static string Module2 {
            get {
                return ResourceManager.GetString("Module2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module 3.
        /// </summary>
        internal static string Module3 {
            get {
                return ResourceManager.GetString("Module3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module 4.
        /// </summary>
        internal static string Module4 {
            get {
                return ResourceManager.GetString("Module4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion.
        /// </summary>
        internal static string Motion {
            get {
                return ResourceManager.GetString("Motion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion Completion (Basic Tuning).
        /// </summary>
        internal static string MotionCompletion {
            get {
                return ResourceManager.GetString("MotionCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion Control.
        /// </summary>
        internal static string MotionControl {
            get {
                return ResourceManager.GetString("MotionControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion Setting.
        /// </summary>
        internal static string MotionSetting {
            get {
                return ResourceManager.GetString("MotionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion Test.
        /// </summary>
        internal static string MotionTest {
            get {
                return ResourceManager.GetString("MotionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor.
        /// </summary>
        internal static string Motor {
            get {
                return ResourceManager.GetString("Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving.
        /// </summary>
        internal static string Moving {
            get {
                return ResourceManager.GetString("Moving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user.
        /// </summary>
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No emission.
        /// </summary>
        internal static string NoEmission {
            get {
                return ResourceManager.GetString("NoEmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Reduction Factor.
        /// </summary>
        internal static string NoiseReductionFactor {
            get {
                return ResourceManager.GetString("NoiseReductionFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Continous.
        /// </summary>
        internal static string NonContinous {
            get {
                return ResourceManager.GetString("NonContinous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Cycles.
        /// </summary>
        internal static string NoOfCycles {
            get {
                return ResourceManager.GetString("NoOfCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notch Filter.
        /// </summary>
        internal static string NotchFilter {
            get {
                return ResourceManager.GetString("NotchFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notch Filter Attenuation.
        /// </summary>
        internal static string NotchFilterAttenuation {
            get {
                return ResourceManager.GetString("NotchFilterAttenuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notch Filter Frequency.
        /// </summary>
        internal static string NotchFilterFrequency {
            get {
                return ResourceManager.GetString("NotchFilterFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notch Filter Width.
        /// </summary>
        internal static string NotchFilterWidth {
            get {
                return ResourceManager.GetString("NotchFilterWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Levels.
        /// </summary>
        internal static string NumLevels {
            get {
                return ResourceManager.GetString("NumLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Live.
        /// </summary>
        internal static string OnLive {
            get {
                return ResourceManager.GetString("OnLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Image.
        /// </summary>
        internal static string OpenImage {
            get {
                return ResourceManager.GetString("OpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational.
        /// </summary>
        internal static string Operational {
            get {
                return ResourceManager.GetString("Operational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        internal static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other settings.
        /// </summary>
        internal static string OtherSettings {
            get {
                return ResourceManager.GetString("OtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output control.
        /// </summary>
        internal static string OutputControl {
            get {
                return ResourceManager.GetString("OutputControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string P {
            get {
                return ResourceManager.GetString("P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phi.
        /// </summary>
        internal static string Phi {
            get {
                return ResourceManager.GetString("Phi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point 1.
        /// </summary>
        internal static string Point1 {
            get {
                return ResourceManager.GetString("Point1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point 2.
        /// </summary>
        internal static string Point2 {
            get {
                return ResourceManager.GetString("Point2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polarization.
        /// </summary>
        internal static string Polarization {
            get {
                return ResourceManager.GetString("Polarization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position and Velocity Loops (Basic Tuning).
        /// </summary>
        internal static string PositionAndVelocityLoops {
            get {
                return ResourceManager.GetString("PositionAndVelocityLoops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Proportional Gain.
        /// </summary>
        internal static string PositionProportionalGain {
            get {
                return ResourceManager.GetString("PositionProportionalGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerlock.
        /// </summary>
        internal static string Powerlock {
            get {
                return ResourceManager.GetString("Powerlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PP Divider.
        /// </summary>
        internal static string PPDivider {
            get {
                return ResourceManager.GetString("PPDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        internal static string Preset {
            get {
                return ResourceManager.GetString("Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset editor.
        /// </summary>
        internal static string PresetEditor {
            get {
                return ResourceManager.GetString("PresetEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process System.
        /// </summary>
        internal static string ProcessSystem {
            get {
                return ResourceManager.GetString("ProcessSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Table.
        /// </summary>
        internal static string ProcessTable {
            get {
                return ResourceManager.GetString("ProcessTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductionEngineer.
        /// </summary>
        internal static string ProductionEngineer {
            get {
                return ResourceManager.GetString("ProductionEngineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P (Proportional Gain).
        /// </summary>
        internal static string ProportionalGainWithShortName {
            get {
                return ResourceManager.GetString("ProportionalGainWithShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse_duration.
        /// </summary>
        internal static string PulseDuration {
            get {
                return ResourceManager.GetString("PulseDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        internal static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius 1.
        /// </summary>
        internal static string Radius1 {
            get {
                return ResourceManager.GetString("Radius1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius 2.
        /// </summary>
        internal static string Radius2 {
            get {
                return ResourceManager.GetString("Radius2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipies.
        /// </summary>
        internal static string Recipies {
            get {
                return ResourceManager.GetString("Recipies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Guide.
        /// </summary>
        internal static string RecoveryGuide {
            get {
                return ResourceManager.GetString("RecoveryGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        internal static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REL.
        /// </summary>
        internal static string Rel {
            get {
                return ResourceManager.GetString("Rel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter new password.
        /// </summary>
        internal static string ReNewPassword {
            get {
                return ResourceManager.GetString("ReNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter password.
        /// </summary>
        internal static string RePassword {
            get {
                return ResourceManager.GetString("RePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        internal static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row 1.
        /// </summary>
        internal static string Row1 {
            get {
                return ResourceManager.GetString("Row1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row 2.
        /// </summary>
        internal static string Row2 {
            get {
                return ResourceManager.GetString("Row2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row center.
        /// </summary>
        internal static string RowCenter {
            get {
                return ResourceManager.GetString("RowCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image.
        /// </summary>
        internal static string SaveImage {
            get {
                return ResourceManager.GetString("SaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Result.
        /// </summary>
        internal static string SaveResult {
            get {
                return ResourceManager.GetString("SaveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll.
        /// </summary>
        internal static string Scroll {
            get {
                return ResourceManager.GetString("Scroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Axis.
        /// </summary>
        internal static string SelectAxisLabel {
            get {
                return ResourceManager.GetString("SelectAxisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected area.
        /// </summary>
        internal static string SelectedArea {
            get {
                return ResourceManager.GetString("SelectedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Status.
        /// </summary>
        internal static string SensorStatus {
            get {
                return ResourceManager.GetString("SensorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Engineer.
        /// </summary>
        internal static string ServiceEngineer {
            get {
                return ResourceManager.GetString("ServiceEngineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set All.
        /// </summary>
        internal static string SetAll {
            get {
                return ResourceManager.GetString("SetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets Damping Denominator.
        /// </summary>
        internal static string SetsDampingDenominator {
            get {
                return ResourceManager.GetString("SetsDampingDenominator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets Damping Numerator.
        /// </summary>
        internal static string SetsDampingNumerator {
            get {
                return ResourceManager.GetString("SetsDampingNumerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets Denominator Frequency.
        /// </summary>
        internal static string SetsDenominatorFrequency {
            get {
                return ResourceManager.GetString("SetsDenominatorFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets Filter Bandwidth.
        /// </summary>
        internal static string SetsFilterBandwidth {
            get {
                return ResourceManager.GetString("SetsFilterBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets Filter Damping.
        /// </summary>
        internal static string SetsFilterDamping {
            get {
                return ResourceManager.GetString("SetsFilterDamping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets Numerator Frequency.
        /// </summary>
        internal static string SetsNumeratorFrequency {
            get {
                return ResourceManager.GetString("SetsNumeratorFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Window Time (ms).
        /// </summary>
        internal static string SettingWindowTimeInMilliseconds {
            get {
                return ResourceManager.GetString("SettingWindowTimeInMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetZero.
        /// </summary>
        internal static string SetZero {
            get {
                return ResourceManager.GetString("SetZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server connection lost. Reconnecting....
        /// </summary>
        internal static string SeverConnectionLostContent {
            get {
                return ResourceManager.GetString("SeverConnectionLostContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to server lost.
        /// </summary>
        internal static string SeverConnectionLostTittle {
            get {
                return ResourceManager.GetString("SeverConnectionLostTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        internal static string Severity {
            get {
                return ResourceManager.GetString("Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape Type.
        /// </summary>
        internal static string ShapeType {
            get {
                return ResourceManager.GetString("ShapeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpness.
        /// </summary>
        internal static string Sharpness {
            get {
                return ResourceManager.GetString("Sharpness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        internal static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standby.
        /// </summary>
        internal static string Standby {
            get {
                return ResourceManager.GetString("Standby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step - Calibration.
        /// </summary>
        internal static string StepCalib {
            get {
                return ResourceManager.GetString("StepCalib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Count.
        /// </summary>
        internal static string StepCount {
            get {
                return ResourceManager.GetString("StepCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Size.
        /// </summary>
        internal static string StepSize {
            get {
                return ResourceManager.GetString("StepSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substrate Chuck Vacuum.
        /// </summary>
        internal static string SubstrateChuckVacuum {
            get {
                return ResourceManager.GetString("SubstrateChuckVacuum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substrate Lifting Module.
        /// </summary>
        internal static string SubstrateLiftingModule {
            get {
                return ResourceManager.GetString("SubstrateLiftingModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch user.
        /// </summary>
        internal static string SwitchUser {
            get {
                return ResourceManager.GetString("SwitchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW Motion Limit (-).
        /// </summary>
        internal static string SWMotionLimitNegative {
            get {
                return ResourceManager.GetString("SWMotionLimitNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW Motion Limit (+).
        /// </summary>
        internal static string SWMotionLimitPositive {
            get {
                return ResourceManager.GetString("SWMotionLimitPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Radius (mm).
        /// </summary>
        internal static string TargetRadiusInMillimeters {
            get {
                return ResourceManager.GetString("TargetRadiusInMillimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teach.
        /// </summary>
        internal static string Teach {
            get {
                return ResourceManager.GetString("Teach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching.
        /// </summary>
        internal static string Teaching {
            get {
                return ResourceManager.GetString("Teaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold.
        /// </summary>
        internal static string Threshold {
            get {
                return ResourceManager.GetString("Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (s).
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Calculate.
        /// </summary>
        internal static string TimeCalculate {
            get {
                return ResourceManager.GetString("TimeCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (s).
        /// </summary>
        internal static string TimeInSeconds {
            get {
                return ResourceManager.GetString("TimeInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Span.
        /// </summary>
        internal static string TimeSpan {
            get {
                return ResourceManager.GetString("TimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip-tilt.
        /// </summary>
        internal static string TipTilt {
            get {
                return ResourceManager.GetString("TipTilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        internal static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger.
        /// </summary>
        internal static string Trigger {
            get {
                return ResourceManager.GetString("Trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tune Settings.
        /// </summary>
        internal static string TuneSettings {
            get {
                return ResourceManager.GetString("TuneSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deg.
        /// </summary>
        internal static string UnitDeg {
            get {
                return ResourceManager.GetString("UnitDeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        internal static string UnitMM {
            get {
                return ResourceManager.GetString("UnitMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloading.
        /// </summary>
        internal static string Unloading {
            get {
                return ResourceManager.GetString("Unloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect..
        /// </summary>
        internal static string UsernameOrPasswordIncorrectMessage {
            get {
                return ResourceManager.GetString("UsernameOrPasswordIncorrectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User role.
        /// </summary>
        internal static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vel.
        /// </summary>
        internal static string Vel {
            get {
                return ResourceManager.GetString("Vel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        internal static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity Low Pass Filter Bandwidth.
        /// </summary>
        internal static string VelocityLowPassFilterBandwidth {
            get {
                return ResourceManager.GetString("VelocityLowPassFilterBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity Proportional Gain.
        /// </summary>
        internal static string VelocityProportionalGain {
            get {
                return ResourceManager.GetString("VelocityProportionalGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision.
        /// </summary>
        internal static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave length.
        /// </summary>
        internal static string WaveLength {
            get {
                return ResourceManager.GetString("WaveLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Balance.
        /// </summary>
        internal static string WhiteBalance {
            get {
                return ResourceManager.GetString("WhiteBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-axis.
        /// </summary>
        internal static string XAxis {
            get {
                return ResourceManager.GetString("XAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0X-axis.
        /// </summary>
        internal static string XAxis0 {
            get {
                return ResourceManager.GetString("XAxis0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-axis (mm).
        /// </summary>
        internal static string XAxisMM {
            get {
                return ResourceManager.GetString("XAxisMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-axis.
        /// </summary>
        internal static string YAxis {
            get {
                return ResourceManager.GetString("YAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0Y-axis.
        /// </summary>
        internal static string YAxis0 {
            get {
                return ResourceManager.GetString("YAxis0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-axis (mm).
        /// </summary>
        internal static string YAxisMM {
            get {
                return ResourceManager.GetString("YAxisMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-axis.
        /// </summary>
        internal static string ZAxis {
            get {
                return ResourceManager.GetString("ZAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-axis (mm).
        /// </summary>
        internal static string ZAxisMM {
            get {
                return ResourceManager.GetString("ZAxisMM", resourceCulture);
            }
        }
    }
}
